-- Production schema hardening for muaesim.vn
-- Run once. MySQL 8+ supports ADD COLUMN/INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS support_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  channel VARCHAR(32) NOT NULL,
  user_key VARCHAR(128) NOT NULL,
  state VARCHAR(64) DEFAULT NULL,
  context_json JSON DEFAULT NULL,
  bot_paused TINYINT(1) NOT NULL DEFAULT 0,
  needs_human TINYINT(1) NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_channel_user (channel, user_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `order`
  ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS emailsent TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iccid VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS orderNo VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS transactionId VARCHAR(128) NULL,
  ADD INDEX IF NOT EXISTS idx_order_order_id (order_id),
  ADD INDEX IF NOT EXISTS idx_order_status (status),
  ADD INDEX IF NOT EXISTS idx_order_iccid (iccid);

ALTER TABLE topup_order
  ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS processed_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS emailsent TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS topup_status TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS provider_response_json MEDIUMTEXT NULL,
  ADD COLUMN IF NOT EXISTS error_message TEXT NULL,
  ADD INDEX IF NOT EXISTS idx_topup_tid (tid),
  ADD INDEX IF NOT EXISTS idx_topup_iccid (iccid),
  ADD INDEX IF NOT EXISTS idx_topup_status (status, topup_status);

ALTER TABLE esimlist
  ADD INDEX IF NOT EXISTS idx_esim_order_id (order_id),
  ADD INDEX IF NOT EXISTS idx_esim_iccid (iccid);
